
-- Constants --

local BattlePass_1_Pool = {}


-- Pool Data --

BattlePass_1_Pool[1] = {
	FreeTrack = "HarpSeal",
	GoldTrack = "LimeSeal",
}

BattlePass_1_Pool[2] = {
	FreeTrack = "BabyBaikalSeal",
	GoldTrack = "Antennae",
}

BattlePass_1_Pool[3] = {
	FreeTrack = "Nerd_Glasses",
	GoldTrack = "RainbowTrail",
}

BattlePass_1_Pool[4] = {
	FreeTrack = "Cow_Boy_Hat",
	GoldTrack = "Crab",
}

BattlePass_1_Pool[5] = {
	FreeTrack = "TurdSeal",
	GoldTrack = "Propeller_Beanie",
}

BattlePass_1_Pool[6] = {
	FreeTrack = "Black_Durag",
	GoldTrack = "GooglyEyes",
}

BattlePass_1_Pool[7] = {
	FreeTrack = "Red_Shutter_Shades",
	GoldTrack = "Hamburger",
}

BattlePass_1_Pool[8] = {
	FreeTrack = "Blue_Ribbon",
	GoldTrack = "Tin_Pot",
}

BattlePass_1_Pool[9] = {
	FreeTrack = "PinkTrail",
	GoldTrack = "LuckyHeadband",
}

BattlePass_1_Pool[10] = {
	FreeTrack = "BaikalSeal",
	GoldTrack = "GrapeSeal",
}

BattlePass_1_Pool[11] = {
	FreeTrack = "Green_Shutter_Shades",
	GoldTrack = "Rubber_Duckie",
}

BattlePass_1_Pool[12] = {
	FreeTrack = "Red_Ribbon",
	GoldTrack = "Unicorn",
}

BattlePass_1_Pool[13] = {
	FreeTrack = "YellowTrail",
	GoldTrack = "NewspaperCap",
}

BattlePass_1_Pool[14] = {
	FreeTrack = "Blue_Durag",
	GoldTrack = "MouseFriend",
}

BattlePass_1_Pool[15] = {
	FreeTrack = "Yellow_Ribbon",
	GoldTrack = "MouseCap",
}

BattlePass_1_Pool[16] = {
	FreeTrack = "ToothpasteTrail",
	GoldTrack = "SpaceSandwich",
}

BattlePass_1_Pool[17] = {
	FreeTrack = "Black_Ribbon",
	GoldTrack = "Thunderstorm",
}

BattlePass_1_Pool[18] = {
	FreeTrack = "Blue_Shutter_Shades",
	GoldTrack = "WingsBlue", 
}

BattlePass_1_Pool[19] = {
	FreeTrack = "Pink_Durag",
	GoldTrack = "Cake",
}

BattlePass_1_Pool[20] = {
	FreeTrack = "Red_Cap",
	GoldTrack = "OrangeSeal",
}

BattlePass_1_Pool[21] = {
	FreeTrack = "Hotdog",
	GoldTrack = "Apple",
}

BattlePass_1_Pool[22] = {
	FreeTrack = "Orange_Durag",
	GoldTrack = "SuperheroMask",
}

BattlePass_1_Pool[23] = {
	FreeTrack = "RedTrail",
	GoldTrack = "Taco",
}

BattlePass_1_Pool[24] = {
	FreeTrack = "MoneyCap",
	GoldTrack = "ChefHat",
}

BattlePass_1_Pool[25] = {
	FreeTrack = "Wings",
	GoldTrack = "BlueberrySeal",
}

BattlePass_1_Pool[26] = {
	FreeTrack = "Pink_Cap",
	GoldTrack = "Sheikh",
}

BattlePass_1_Pool[27] = {
	FreeTrack = "iLoveMom",
	GoldTrack = "YellowFish",
}

BattlePass_1_Pool[28] = {
	FreeTrack = "GreenTrail",
	GoldTrack = "CrazyGlasses",
}

BattlePass_1_Pool[29] = {
	FreeTrack = "Purple_Shutter_Shades",
	GoldTrack = "Pizza",
}

BattlePass_1_Pool[30] = {
	FreeTrack = "Green_Cap",
	GoldTrack = "BubblegumSeal",
}

BattlePass_1_Pool[31] = {
	FreeTrack = "PartyCap",
	GoldTrack = "WingsRed",
}

BattlePass_1_Pool[32] = {
	FreeTrack = "RoundShades",
	GoldTrack = "3DGlasses",
}

BattlePass_1_Pool[33] = {
	FreeTrack = "BlueTrail",
	GoldTrack = "ChocolateMilk",
}

BattlePass_1_Pool[34] = {
	FreeTrack = "LoveShades",
	GoldTrack = "Sunflower",
}

BattlePass_1_Pool[35] = {
	FreeTrack = "ScubaGearBlue",
	GoldTrack = "LemonSeal",
}

BattlePass_1_Pool[36] = {
	FreeTrack = "GolfCap",
	GoldTrack = "Fish",
}

BattlePass_1_Pool[37] = {
	FreeTrack = "BirdsNest",
	GoldTrack = "BowlCap",
}

BattlePass_1_Pool[38] = {
	FreeTrack = "Black_Cap",
	GoldTrack = "WingsGold",
}

BattlePass_1_Pool[39] = {
	FreeTrack = "LuckyShades",
	GoldTrack = "RedGlasses",
}

BattlePass_1_Pool[40] = {
	FreeTrack = "Red_Durag",
	GoldTrack = "CottonCandySeal",
}

BattlePass_1_Pool[41] = {
	FreeTrack = "PurpleTrail",
	GoldTrack = "WingsOfDuality",
}

BattlePass_1_Pool[42] = {
	FreeTrack = "OrangeTrail",
	GoldTrack = "SwordProp",
}

BattlePass_1_Pool[43] = {
	FreeTrack = "Shades",
	GoldTrack = "Flamingo",
}

BattlePass_1_Pool[44] = {
	FreeTrack = "Blue_Cap",
	GoldTrack = "Bomb",
}

BattlePass_1_Pool[45] = {
	FreeTrack = "ScubaGearOrange",
	GoldTrack = "StrawberrySeal",
}

BattlePass_1_Pool[46] = {
	FreeTrack = "PrisonerCap",
	GoldTrack = "FloppyFish",
}

BattlePass_1_Pool[47] = {
	FreeTrack = "PoliceCap",
	GoldTrack = "NarwhalHat",
}

BattlePass_1_Pool[48] = {
	FreeTrack = "HeartHat",
	GoldTrack = "Crow",
}

BattlePass_1_Pool[49] = {
	FreeTrack = "Banana",
	GoldTrack = "GoldTopHat",
}

BattlePass_1_Pool[50] = {
	FreeTrack = "SilverSeal",
	GoldTrack = "GoldSeal",
}
-- Setup --

return BattlePass_1_Pool