
-- Settings --

local DummyDirectory = {
	Shirts = {
		"Green_Scarf",
		"Pink_Scarf",
		"Blue_Hoodie",
		"Yellow_Hoodie",
		"White_Kimono",
		"Blue_Bomber",
		"Cozy_Knitted_Sweater",
		"Dungarees"
	},
	
	Hats = {
		"Black_Beanie",
		"Green_Beanie",
		"Red_Beanie",
		"Ice_Crown",
		"Ushanka",
		"Black_Cap",
		"Red_Cap"
	},
	
	Glasses = {
		"Sick_Glasses",
		"Carti"
	},
	
	



}



-- Setup --

return DummyDirectory
