
local ItemDirectory = {}

----------------------------------------------------------------------------------------------------
-- EMOTES
----------------------------------------------------------------------------------------------------

ItemDirectory["EmoteWave"] = {
	FlavorText = "Wave",
	Rarity = "Common",
	IconID = "rbxassetid://137413704456388",
	ItemType = "Emotes",
	SpecialData = {}
}

ItemDirectory["EmoteSpin"] = {
	FlavorText = "360 Spin",
	Rarity = "Uncommon",
	IconID = "rbxassetid://86745004396825",
	ItemType = "Emotes",
	SpecialData = {}
}

ItemDirectory["EmoteBounce"] = {
	FlavorText = "Bounce",
	Rarity = "Legendary",
	IconID = "rbxassetid://89863904333225",
	ItemType = "Emotes",
	SpecialData = {}
}

ItemDirectory["EmoteDance"] = {
	FlavorText = "Dance",
	Rarity = "Common",
	IconID = "rbxassetid://108048169540263",
	ItemType = "Emotes",
	SpecialData = {LoopingAnimation = true}
}

ItemDirectory["EmoteOrangeJustice"] = {
	FlavorText = "Orange Justice",
	Rarity = "Rare",
	IconID = "rbxassetid://118273385193726",
	ItemType = "Emotes",
	SpecialData = {LoopingAnimation = true}
}

ItemDirectory["EmoteBackflip"] = {
	FlavorText = "Backflip",
	Rarity = "Common",
	IconID = "rbxassetid://108048169540263",
	ItemType = "Emotes",
	SpecialData = {}
}
----------------------------------------------------------------------------------------------------
-- SEAL SKINS
----------------------------------------------------------------------------------------------------
ItemDirectory["BeeSeal"] = {
	FlavorText = "Bee Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://140435222266297",
	ItemType = "SealSkins",
	SpecialData = {}
}


ItemDirectory["HarpSeal"] = {
	FlavorText = "Harp Seal",
	Rarity = "Common",
	IconID = "rbxassetid://140104884009553",
	ItemType = "SealSkins",
	SpecialData = {}
}


ItemDirectory["BabyBaikalSeal"] = {
	FlavorText = "Baby Baikal Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://108730926711658",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["BaikalSeal"] = {
	FlavorText = "Baikal Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://122232464296452",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["RingedSeal"] = {
	FlavorText = "Ringed Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://81279918237334",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["CottonCandySeal"] = {
	FlavorText = "Cotton Candy Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://73273874667341",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["BubblegumSeal"] = {
	FlavorText = "Bubblegum Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://99373883685874",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["TurdSeal"] = {
	FlavorText = "Turd Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://101926077305351",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["StrawberrySeal"] = {
	FlavorText = "Strawberry Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://74675096753039",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["OrangeSeal"] = {
	FlavorText = "Orange Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://103912764822877",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["LimeSeal"] = {
	FlavorText = "Lime Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://97651126221373",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["LemonSeal"] = {
	FlavorText = "Lemon Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://87352200376262",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["GrapeSeal"] = {
	FlavorText = "Grape Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://127736835837087",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["BlueberrySeal"] = {
	FlavorText = "Blueberry Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://84955400452422",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["GoldSeal"] = {
	FlavorText = "Golden Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://80349368051335",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["SilverSeal"] = {
	FlavorText = "Silver Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://86981305168892",
	ItemType = "SealSkins",
	SpecialData = {}
}

-- new additions

ItemDirectory["CowSeal"] = {
	FlavorText = "Cow Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://78063107211944",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["RibbonSeal"] = {
	FlavorText = "Ribbon Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://125851629851151",
	ItemType = "SealSkins",
	SpecialData = {}
}


ItemDirectory["GirlSeal"] = {
	FlavorText = "Girl Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://77119963482638",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["CheetahSeal"] = {
	FlavorText = "Cheetah Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://71994851941815",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["CheetosSeal"] = {
	FlavorText = "Cheetos Seal",
	Rarity = "Rare",
	IconID = "rbxassetid://91256999519909",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["GalaxySeal"] = {
	FlavorText = "Galaxy Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://103190591693633",
	ItemType = "SealSkins",
	SpecialData = {}
}

ItemDirectory["TieDyeSeal"] = {
	FlavorText = "Tie Dye Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://132305085049153",
	ItemType = "SealSkins",
	SpecialData = {}
}
ItemDirectory["WatermelonSeal"] = {
	FlavorText = "Watermelon Seal",
	Rarity = "Legendary",
	IconID = "rbxassetid://97575493564835",
	ItemType = "SealSkins",
	SpecialData = {}
}
----------------------------------------------------------------------------------------------------
-- GLASSES
----------------------------------------------------------------------------------------------------

ItemDirectory["Black_Sunglasses"] = {
	FlavorText = "Black Shades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://129868231197628",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Carti"] = {
	FlavorText = "Clout Goggles",
	Rarity = "Rare",
	IconID = "rbxassetid://116644687419447",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["404_Vr"] = {
	FlavorText = "Error 404",
	Rarity = "Rare",
	IconID = "rbxassetid://117353580293140",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Yellow_Color_Vr"] = {
	FlavorText = "Yellow Error VR",
	Rarity = "Rare",
	IconID = "rbxassetid://139862200116847",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}


ItemDirectory["Noise_Vr"] = {
	FlavorText = "Noise VR",
	Rarity = "Rare",
	IconID = "rbxassetid://118246186660868",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Purple_Color_Vr"] = {
	FlavorText = "Purple Error VR",
	Rarity = "Rare",
	IconID = "rbxassetid://130025976543091",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Sick_Glasses"] = {
	FlavorText = "Epic Shades",
	Rarity = "Legendary",
	IconID = "rbxassetid://70402774734514",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Skull_Mask"] = {
	FlavorText = "Skull Mask",
	Rarity = "Rare",
	IconID = "rbxassetid://136984188438140",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Pink_Heart_Shutter_Shades"] = {
	FlavorText = "Pink Shutter Shades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://128250761219377",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Green_Shutter_Shades"] = {
	FlavorText = "Green Shutter Shades",
	Rarity = "Common",
	IconID = "rbxassetid://110185183585415",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Red_Shutter_Shades"] = {
	FlavorText = "Red Shutter Shades",
	Rarity = "Common",
	IconID = "rbxassetid://122349805975184",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Blue_Shutter_Shades"] = {
	FlavorText = "Blue Shutter Shades",
	Rarity = "Common",
	IconID = "rbxassetid://94071962888545",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Purple_Shutter_Shades"] = {
	FlavorText = "Purple Shutter Shades",
	Rarity = "Common",
	IconID = "rbxassetid://74740697283206",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Mustache"] = {
	FlavorText = "Mustache",
	Rarity = "Uncommon",
	IconID = "rbxassetid://110296195570154",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Nerd_Glasses"] = {
	FlavorText = "Nerd Glasses",
	Rarity = "Common",
	IconID = "rbxassetid://77343881794985",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Face"
	}
}


----------------------------------------------------------------------------------------------------
-- HATS
----------------------------------------------------------------------------------------------------
ItemDirectory["witchHat"] = {
	FlavorText = "Witch Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://125458365396823",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["classicPumpkin"] = {
	FlavorText = "Pumpkin Head",
	Rarity = "Rare",
	IconID = "rbxassetid://76259053332015",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["halloweenJester"] = {
	FlavorText = "Halloween Jester",
	Rarity = "Rare",
	IconID = "rbxassetid://97891246065855",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["UFO"] = {
	FlavorText = "UFO",
	Rarity = "Rare",
	IconID = "rbxassetid://108718434096497",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["PirateCap"] = {
	FlavorText = "Pirate's Cap",
	Rarity = "Rare",
	IconID = "rbxassetid://124590537626461",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["SailorCap"] = {
	FlavorText = "Sailor's Cap",
	Rarity = "Rare",
	IconID = "rbxassetid://76423010223210",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["Sprout"] = {
	FlavorText = "Sprout",
	Rarity = "Rare",
	IconID = "rbxassetid://117176369084446",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BeeAntennae"] = {
	FlavorText = "Bee Antennae",
	Rarity = "Rare",
	IconID = "rbxassetid://115289146090181",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BeeFlower"] = {
	FlavorText = "Flower",
	Rarity = "Rare",
	IconID = "rbxassetid://74240003396486",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}ItemDirectory["BeeWings"] = {
	FlavorText = "Bee Wings",
	Rarity = "Legendary",
	IconID = "rbxassetid://108606125768026",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["CrabHat"] = {
	FlavorText = "Crab Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://75270145470051",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["BlackIronCrown"] = {
	FlavorText = "Black Iron Crown of Pwnage",
	Rarity = "Legendary",
	IconID = "rbxassetid://123419027045618",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["PaintballTrophy"] = {
	FlavorText = "Classic Trophy",
	Rarity = "Legendary",
	IconID = "rbxassetid://130201018755818",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["PrincessGlasses"] = {
	FlavorText = "Princess Sunglasses",
	Rarity = "Rare",
	IconID = "rbxassetid://131814269941249",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
ItemDirectory["PrincessHat"] = {
	FlavorText = "Princess Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://118392554710950",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["TailGubby"] = {
	FlavorText = "Tail Gubby",
	Rarity = "Uncommon",
	IconID = "rbxassetid://103747231567004",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["gubby"] = {
	FlavorText = "Gubby",
	Rarity = "Uncommon",
	IconID = "rbxassetid://82374202006208",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["ClownNose"] = {
	FlavorText = "Clown",
	Rarity = "Rare",
	IconID = "rbxassetid://125773712960386",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["PrevHat"] = {
	FlavorText = "Prevatic's Top Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://139053083887191",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["DoubleRainbow"] = {
	FlavorText = "Double Rainbow",
	Rarity = "Rare",
	IconID = "rbxassetid://77971085461273",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}


ItemDirectory["SappyFriend"] = {
	FlavorText = "Sappy Friend",
	Rarity = "Common",
	IconID = "rbxassetid://74868984176507",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BlueWinterCap"] = {
	FlavorText = "Blue Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://89475900914571",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["MiniSeal"] = {
	FlavorText = "Mini Seal",
	Rarity = "Common",
	IconID = "rbxassetid://125439660657381",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Yellow_Ribbon"] = {
	FlavorText = "Yellow Ribbon",
	Rarity = "Common",
	IconID = "rbxassetid://108527290633086",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pink_Ribbon"] = {
	FlavorText = "Pink Ribbon",
	Rarity = "Common",
	IconID = "rbxassetid://89477060398093",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Ribbon"] = {
	FlavorText = "Black Ribbon",
	Rarity = "Common",
	IconID = "rbxassetid://103952176025550",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Blue_Ribbon"] = {
	FlavorText = "Blue Ribbon",
	Rarity = "Common",
	IconID = "rbxassetid://80636889580937",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Red_Ribbon"] = {
	FlavorText = "Red Ribbon",
	Rarity = "Common",
	IconID = "rbxassetid://89660174578961",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BlackWinterCap"] = {
	FlavorText = "Black Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://137315270599732",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Italian_Ski_Cap"] = {
	FlavorText = "Ski Cap",
	Rarity = "Common",
	IconID = "rbxassetid://121887827350468",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Orange_Winter_Cap"] = {
	FlavorText = "Orange Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://105001752320553",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pink_Winter_Cap"] = {
	FlavorText = "Pink Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://131158857866963",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Red_Winter_Cap"] = {
	FlavorText = "Red Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://90510056097514",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Ushanka"] = {
	FlavorText = "Ushanka",
	Rarity = "Common",
	IconID = "rbxassetid://71067218963501",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["WcDonaldsCap"] = {
	FlavorText = "WcDonalds Cap",
	Rarity = "Legendary",
	IconID = "rbxassetid://114338050173478",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Fedora"] = {
	FlavorText = "Fedora",
	Rarity = "Uncommon",
	IconID = "rbxassetid://119472527706617",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Tin_Pot"] = {
	FlavorText = "Tin Pot",
	Rarity = "Uncommon",
	IconID = "rbxassetid://131092499348019",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Firefighter_Helmet"] = {
	FlavorText = "Firefighter Helmet",
	Rarity = "Uncommon",
	IconID = "rbxassetid://106792542922711",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Question_Mark"] = {
	FlavorText = "Question Mark",
	Rarity = "Uncommon",
	IconID = "rbxassetid://92086004269279",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BC_Hard_Hat"] = {
	FlavorText = "Hard Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://128074133630168",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Flower_Crown"] = {
	FlavorText = "Flower Crown",
	Rarity = "Uncommon",
	IconID = "rbxassetid://129594110160117",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Ice_Cream"] = {
	FlavorText = "Ice Cream",
	Rarity = "Uncommon",
	IconID = "rbxassetid://86650864439110",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Whipped_Cream_Hat"] = {
	FlavorText = "Whipped Cream Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://90327556742841",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}


ItemDirectory["Traffic_Cone"] = {
	FlavorText = "Traffic Cone",
	Rarity = "Uncommon",
	IconID = "rbxassetid://139801173928851",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Red_Traffic_Cone"] = {
	FlavorText = "Red Traffic Cone",
	Rarity = "Uncommon",
	IconID = "rbxassetid://137709505773473",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}


ItemDirectory["Cheese"] = {
	FlavorText = "Cheese",
	Rarity = "Uncommon",
	IconID = "rbxassetid://77029998607827",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Bunny_Ears"] = {
	FlavorText = "Bunny Ears",
	Rarity = "Uncommon",
	IconID = "rbxassetid://97899672354938",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Kitty_Ears"] = {
	FlavorText = "Kitty Ears",
	Rarity = "Uncommon",
	IconID = "rbxassetid://79427972125593",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["MooseAntlers"] = {
	FlavorText = "Moose",
	Rarity = "Uncommon",
	IconID = "rbxassetid://138281910443235",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Rubber_Duckie"] = {
	FlavorText = "Rubber Ducky",
	Rarity = "Uncommon",
	IconID = "rbxassetid://102911037830572",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Security_Camera"] = {
	FlavorText = "Security Camera",
	Rarity = "Rare",
	IconID = "rbxassetid://95729150007059",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Santa_Hat"] = {
	FlavorText = "Santa Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://128453198693372",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Elf_Hat"] = {
	FlavorText = "Santa Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://107115473495217",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BlueBandedTophat"] = {
	FlavorText = "Blue Top Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://75729598894775",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pink_Banded_Top_Hat"] = {
	FlavorText = "Pink Top Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://135970044348822",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pirate_Hat"] = {
	FlavorText = "Pirate Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://84118830914009",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Flower_Power"] = {
	FlavorText = "Flower Power",
	Rarity = "Rare",
	IconID = "rbxassetid://83732078061065",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pink_Derby_Hat"] = {
	FlavorText = "Pink Derby Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://134255182517845",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Teddy_Bear_Hat"] = {
	FlavorText = "Teddy Bear Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://120360679834143",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Propeller_Beanie"] = {
	FlavorText = "Propeller Beanie",
	Rarity = "Rare",
	IconID = "rbxassetid://135899316642818",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Gem_Crown"] = {
	FlavorText = "Gem Crown",
	Rarity = "Rare",
	IconID = "rbxassetid://128786415782030",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Domino_Crown"] = {
	FlavorText = "Domino Crown",
	Rarity = "Legendary",
	IconID = "rbxassetid://100934225498296",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Golden_Top_Hat_of_BlingBling"] = {
	FlavorText = "Golden Top Hat of Bling Bling",
	Rarity = "Legendary",
	IconID = "rbxassetid://72063147376088",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Clockwork_Shades"] = {
	FlavorText = "Clockwork's Shades",
	Rarity = "Legendary",
	IconID = "rbxassetid://129321448484290",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Roblox_Golden_Crown"] = {
	FlavorText = "Golden Crown",
	Rarity = "Legendary",
	IconID = "rbxassetid://94355946152367",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["GoldWinterCap"] = {
	FlavorText = "Gold Beanie",
	Rarity = "Legendary",
	IconID = "rbxassetid://123093192341733",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Fat_Sign"] = {
	FlavorText = "FAT Sign",
	Rarity = "Legendary",
	IconID = "rbxassetid://79741129584893",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Stupid_Sign"] = {
	FlavorText = "Stupid Sign",
	Rarity = "Legendary",
	IconID = "rbxassetid://140223878135014",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Chud_Sign"] = {
	FlavorText = "Chud Sign",
	Rarity = "Legendary",
	IconID = "rbxassetid://118855154783691",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Noob_Sign"] = {
	FlavorText = "Noob Sign",
	Rarity = "Legendary",
	IconID = "rbxassetid://116203346947647",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Antlers"] = {
	FlavorText = "Antlers",
	Rarity = "Rare",
	IconID = "rbxassetid://135417719801532",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["SealAntlers"] = {
	FlavorText = "Seal Antlers",
	Rarity = "Rare",
	IconID = "rbxassetid://140341183267583",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Arrowhead"] = {
	FlavorText = "Arrow",
	Rarity = "Legendary",
	IconID = "rbxassetid://73320690732366",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Bear_Ears"] = {
	FlavorText = "Bear Ears",
	Rarity = "Rare",
	IconID = "rbxassetid://90813870045121",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Beret"] = {
	FlavorText = "Beret",
	Rarity = "Uncommon",
	IconID = "rbxassetid://100864495298198",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Bucket_Hat"] = {
	FlavorText = "Black Bucket Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://139232415376053",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Cap"] = {
	FlavorText = "Black Cap",
	Rarity = "Common",
	IconID = "rbxassetid://116515684307357",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Cap_Tiny"] = {
	FlavorText = "Tiny Black Cap",
	Rarity = "Rare",
	IconID = "rbxassetid://94556791133966",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Propeller_Beanie_Tiny"] = {
	FlavorText = "Tiny Propeller Beanie",
	Rarity = "Rare",
	IconID = "rbxassetid://85950400613088",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Beret_Tiny"] = {
	FlavorText = "Tiny Beret",
	Rarity = "Rare",
	IconID = "rbxassetid://96165454777546",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["SealCowboyHat_Tiny"] = {
	FlavorText = "Tiny Cowboy Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://118545242591272",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BlueWinterCap_Tiny"] = {
	FlavorText = "Tiny Blue Beanie",
	Rarity = "Rare",
	IconID = "rbxassetid://94889302637678",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["No_Face_Mask"] = {
	FlavorText = "Mask",
	Rarity = "Rare",
	IconID = "rbxassetid://95754084308314",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Durag"] = {
	FlavorText = "Black Durag",
	Rarity = "Common",
	IconID = "rbxassetid://94187016865820",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Frog_Bucket_Hat"] = {
	FlavorText = "Black Frog Bucket Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://137183870833696",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Black_Ninja_Headband"] = {
	FlavorText = "Black Ninja Headband",
	Rarity = "Rare",
	IconID = "rbxassetid://102190732482281",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Blue_Durag"] = {
	FlavorText = "Blue Durag",
	Rarity = "Common",
	IconID = "rbxassetid://103339379487862",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Bowl_Cut"] = {
	FlavorText = "Bowl Cut",
	Rarity = "Rare",
	IconID = "rbxassetid://88068016686004",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Cow_Boy_Hat"] = {
	FlavorText = "Cowboy Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://105260123473160",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["SealCowboyHat"] = {
	FlavorText = "Seal CowboyHat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://84379885905326",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Dunce_Hat"] = {
	FlavorText = "Dunce Cap",
	Rarity = "Legendary",
	IconID = "rbxassetid://104801750982499",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Golden_Bowl_Cut"] = {
	FlavorText = "Golden Bowl Cut",
	Rarity = "Legendary",
	IconID = "rbxassetid://73166472180439",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Golden_Crown"] = {
	FlavorText = "Golden Crown",
	Rarity = "Legendary",
	IconID = "rbxassetid://114861141549797",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Halo"] = {
	FlavorText = "Halo",
	Rarity = "Legendary",
	IconID = "rbxassetid://114494552973104",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Headphones"] = {
	FlavorText = "Black Headphones",
	Rarity = "Rare",
	IconID = "rbxassetid://135002764120149",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Ice_Crown"] = {
	FlavorText = "Ice Crown",
	Rarity = "Legendary",
	IconID = "rbxassetid://79186772467612",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Laurel"] = {
	FlavorText = "Laurel",
	Rarity = "Legendary",
	IconID = "rbxassetid://78633578981889",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pumpkin_Head"] = {
	FlavorText = "Pumpkin Head",
	Rarity = "Rare",
	IconID = "rbxassetid://108617554116263",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Red_Cap"] = {
	FlavorText = "Red Cap",
	Rarity = "Common",
	IconID = "rbxassetid://102820193263852",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Blue_Cap"] = {
	FlavorText = "Blue Cap",
	Rarity = "Common",
	IconID = "rbxassetid://115137556974297",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pink_Cap"] = {
	FlavorText = "Pink Cap",
	Rarity = "Common",
	IconID = "rbxassetid://77764570041027",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Green_Cap"] = {
	FlavorText = "Green Cap",
	Rarity = "Common",
	IconID = "rbxassetid://136641060765194",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Red_Durag"] = {
	FlavorText = "Red Durag",
	Rarity = "Common",
	IconID = "rbxassetid://124129476025579",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Orange_Durag"] = {
	FlavorText = "Orange Durag",
	Rarity = "Common",
	IconID = "rbxassetid://134114612209079",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pink_Durag"] = {
	FlavorText = "Pink Durag",
	Rarity = "Common",
	IconID = "rbxassetid://108636876150923",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Red_Ninja_Headband"] = {
	FlavorText = "Red Ninja Headband",
	Rarity = "Rare",
	IconID = "rbxassetid://78830758466143",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Mushroom"] = {
	FlavorText = "Mushroom",
	Rarity = "Rare",
	IconID = "rbxassetid://122644101228959",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Sombrero"] = {
	FlavorText = "Sombrero",
	Rarity = "Uncommon",
	IconID = "rbxassetid://106400897152947",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Witch_Hat"] = {
	FlavorText = "Witch Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://77298182243545",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["SappyHead"] = {
	FlavorText = "Sappy Head",
	Rarity = "Rare",
	IconID = "rbxassetid://100379766909334",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["MelonHead"] = {
	FlavorText = "Melon Head",
	Rarity = "Rare",
	IconID = "rbxassetid://91475493562567",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["StarShutters"] = {
	FlavorText = "Starry Shutter Shades",
	Rarity = "Legendary",
	IconID = "rbxassetid://123828076220165",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["VegetableHat"] = {
	FlavorText = "Plant",
	Rarity = "Rare",
	IconID = "rbxassetid://95261732439874",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}
----------------------------------------------------------------------------------------------------
-- Trails
----------------------------------------------------------------------------------------------------
ItemDirectory["FlowerTrail"] = {
	FlavorText = "Flower Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://92692762366737",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["StarTrail"] = {
	FlavorText = "Galaxy Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://76901933255694",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["BeachTrail"] = {
	FlavorText = "Beach Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://72867248033683",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["BlackTrail"] = {
	FlavorText = "Black Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://107434667860425",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["BlueTrail"] = {
	FlavorText = "Blue Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://89139749313905",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["CloudyTrail"] = {
	FlavorText = "Cloudy Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://106558878406695",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["CoinTrail"] = {
	FlavorText = "Coin Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://76812718905161",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["EerieTrail"] = {
	FlavorText = "Eerie Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://136417795869020",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["FireTrail"] = {
	FlavorText = "Fire Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://81555707255577",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["GreenTrail"] = {
	FlavorText = "Green Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://112013041455993",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["IceTrail"] = {
	FlavorText = "Ice Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://99998165719771",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["LightningTrail"] = {
	FlavorText = "Lightning Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://135816809529510",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["OrangeTrail"] = {
	FlavorText = "Orange Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://100182200754289",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["PinkTrail"] = {
	FlavorText = "Pink Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://79077109735280",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["PurpleTrail"] = {
	FlavorText = "Purple Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://133958320616515",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["RainbowTrail"] = {
	FlavorText = "Rainbow Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://127674825195783",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["RedTrail"] = {
	FlavorText = "Red Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://87404804253019",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["RobuxTrail"] = {
	FlavorText = "Robux Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://128116345469331",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["TixTrail"] = {
	FlavorText = "Tix Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://135108083385548",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["ToothpasteTrail"] = {
	FlavorText = "Toothpaste Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://110904959254530",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["WatermelonTrail"] = {
	FlavorText = "Watermelon Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://107165464325684",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["WhiteTrail"] = {
	FlavorText = "White Trail",
	Rarity = "Rare",
	IconID = "rbxassetid://128789499167945",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["YellowTrail"] = {
	FlavorText = "Yellow Trail",
	Rarity = "Uncommon",
	IconID = "rbxassetid://108974830662351",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}


----------------------------------------------------------------------------------------------------
-- MISCELLANEOUS
----------------------------------------------------------------------------------------------------

ItemDirectory["Coins"] = {
	FlavorText = "Coins",
	Rarity = "Legendary",
	IconID = "rbxassetid://126556997920262",
	ItemType = "Miscellaneous",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}



----------------------------------------------------------------------------------------------------
-- BATTLE PASS
----------------------------------------------------------------------------------------------------

ItemDirectory["3DGlasses"] = {
	FlavorText = "3DGlasses",
	Rarity = "Rare",
	IconID = "rbxassetid://117472080330675",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Antennae"] = {
	FlavorText = "Antennae",
	Rarity = "Uncommon",
	IconID = "rbxassetid://123080540917661",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Apple"] = {
	FlavorText = "Apple",
	Rarity = "Uncommon",
	IconID = "rbxassetid://98250900619783",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Banana"] = {
	FlavorText = "Banana",
	Rarity = "Rare",
	IconID = "rbxassetid://105495024301247",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BirdsNest"] = {
	FlavorText = "BirdsNest",
	Rarity = "Uncommon",
	IconID = "rbxassetid://117935769290849",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Bomb"] = {
	FlavorText = "Bomb",
	Rarity = "Rare",
	IconID = "rbxassetid://132753672903353",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["BowlCap"] = {
	FlavorText = "BowlCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://70563253606810",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Cake"] = {
	FlavorText = "Cake",
	Rarity = "Uncommon",
	IconID = "rbxassetid://113885138499120",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["ChefHat"] = {
	FlavorText = "ChefHat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://87667425924253",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["ChocolateMilk"] = {
	FlavorText = "ChocolateMilk",
	Rarity = "Uncommon",
	IconID = "rbxassetid://79943728188906",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Crab"] = {
	FlavorText = "Crab",
	Rarity = "Rare",
	IconID = "rbxassetid://110879669858851",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["CrazyGlasses"] = {
	FlavorText = "CrazyGlasses",
	Rarity = "Rare",
	IconID = "rbxassetid://99546703597448",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Crow"] = {
	FlavorText = "Crow",
	Rarity = "Rare",
	IconID = "rbxassetid://76202918656387",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Fish"] = {
	FlavorText = "Fish",
	Rarity = "Uncommon",
	IconID = "rbxassetid://132317586051015",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Flamingo"] = {
	FlavorText = "Flamingo",
	Rarity = "Uncommon",
	IconID = "rbxassetid://79021468270881",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["FloppyFish"] = {
	FlavorText = "FloppyFish",
	Rarity = "Uncommon",
	IconID = "rbxassetid://100284783234842",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["GolfCap"] = {
	FlavorText = "GolfCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://137620182398833",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["GooglyEyes"] = {
	FlavorText = "GooglyEyes",
	Rarity = "Rare",
	IconID = "rbxassetid://108444796438615",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Hamburger"] = {
	FlavorText = "Hamburger",
	Rarity = "Uncommon",
	IconID = "rbxassetid://95441911632698",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["HeartHat"] = {
	FlavorText = "HeartHat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://76592147279805",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Hotdog"] = {
	FlavorText = "Hotdog",
	Rarity = "Uncommon",
	IconID = "rbxassetid://81098120052922",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["LoveShades"] = {
	FlavorText = "LoveShades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://78265679995022",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["LuckyHeadband"] = {
	FlavorText = "LuckyHeadband",
	Rarity = "Uncommon",
	IconID = "rbxassetid://136883426450001",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["LuckyShades"] = {
	FlavorText = "LuckyShades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://102567624090920",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["MoneyCap"] = {
	FlavorText = "MoneyCap",
	Rarity = "Rare",
	IconID = "rbxassetid://136559261544036",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["MouseCap"] = {
	FlavorText = "MouseCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://120213163621377",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["MouseFriend"] = {
	FlavorText = "MouseFriend",
	Rarity = "Rare",
	IconID = "rbxassetid://134964552852209",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["NarwhalHat"] = {
	FlavorText = "NarwhalHat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://109371701709235",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["NewspaperCap"] = {
	FlavorText = "NewspaperCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://73558896664203",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["PartyCap"] = {
	FlavorText = "PartyCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://73558896664203",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Pizza"] = {
	FlavorText = "Pizza",
	Rarity = "Uncommon",
	IconID = "rbxassetid://116047637089564",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["PoliceCap"] = {
	FlavorText = "PoliceCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://116516816193708",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["PrisonerCap"] = {
	FlavorText = "PrisonerCap",
	Rarity = "Uncommon",
	IconID = "rbxassetid://90462728217276",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["RedGlasses"] = {
	FlavorText = "RedGlasses",
	Rarity = "Uncommon",
	IconID = "rbxassetid://88190221927895",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["RoundShades"] = {
	FlavorText = "RoundShades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://93010794668582",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["ScubaGearBlue"] = {
	FlavorText = "Blue Scuba Gear",
	Rarity = "Uncommon",
	IconID = "rbxassetid://87218815297414",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["ScubaGearOrange"] = {
	FlavorText = "Orange Scuba Gear",
	Rarity = "Uncommon",
	IconID = "rbxassetid://106744280525651",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Shades"] = {
	FlavorText = "Shades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://97120373108020",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["Sheikh"] = {
	FlavorText = "Sheikh",
	Rarity = "Uncommon",
	IconID = "rbxassetid://121071743082297",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["SpaceSandwich"] = {
	FlavorText = "SpaceSandwich",
	Rarity = "Uncommon",
	IconID = "rbxassetid://90114520129658",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Sunflower"] = {
	FlavorText = "Sunflower",
	Rarity = "Uncommon",
	IconID = "rbxassetid://106317521917956",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["SuperheroMask"] = {
	FlavorText = "SuperheroMask",
	Rarity = "Uncommon",
	IconID = "rbxassetid://107114828376408",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Face"
	}
}

ItemDirectory["SwordProp"] = {
	FlavorText = "SwordProp",
	Rarity = "Uncommon",
	IconID = "rbxassetid://109287673325713",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Taco"] = {
	FlavorText = "Taco",
	Rarity = "Uncommon",
	IconID = "rbxassetid://119682314448131",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Thunderstorm"] = {
	FlavorText = "Thunderstorm",
	Rarity = "Rare",
	IconID = "rbxassetid://86824102757531",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Unicorn"] = {
	FlavorText = "Unicorn",
	Rarity = "Rare",
	IconID = "rbxassetid://137282507207221",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["Wings"] = {
	FlavorText = "Wings",
	Rarity = "Legendary",
	IconID = "rbxassetid://100281964191832",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["WingsBlue"] = {
	FlavorText = "Blue Wings",
	Rarity = "Rare",
	IconID = "rbxassetid://107694667814177",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["WingsRed"] = {
	FlavorText = "Red Wings",
	Rarity = "Rare",
	IconID = "rbxassetid://102575219551722",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["WingsGold"] = {
	FlavorText = "Golden Wings",
	Rarity = "Legendary",
	IconID = "rbxassetid://70568558264315",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["WingsOfDuality"] = {
	FlavorText = "Wings of Duality",
	Rarity = "Rare",
	IconID = "rbxassetid://127509216771760",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["YellowFish"] = {
	FlavorText = "YellowFish",
	Rarity = "Rare",
	IconID = "rbxassetid://79563126854981",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}

ItemDirectory["iLoveMom"] = {
	FlavorText = "iLoveMom",
	Rarity = "Uncommon",
	IconID = "rbxassetid://95260982186616",
	ItemType = "Accessory",
	ItemModel = nil,
	SpecialData = {
		AccessoryType = "Hat"
	}
}


ItemDirectory["GoldTopHat"] = {
	FlavorText = "Golden Top Hat",
	Rarity = "Legendary",
	IconID = "rbxassetid://120033881191021",
	ItemType = "Accessory",
	SpecialData = {
		AccessoryType = "Hat"
	}
}



----------------------------------------------------------------------------------------------------
-- Setup --
----------------------------------------------------------------------------------------------------
return ItemDirectory