local ItemDirectory = {}

----------------------------------------------------------------------------------------------------
-- FACIALEXPRESSIONS
----------------------------------------------------------------------------------------------------

ItemDirectory["Angry_Face"] = {
	FlavorText = "Devious",
	Rarity = "Rare",
	IconID = "rbxassetid://86435971059553",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Angry_Face"],
	SpecialData = {
		HeadType = "HeadFlat",
	}
}

ItemDirectory["Dizzy_Face"] = {
	FlavorText = "Dizzy",
	Rarity = "Rare",
	IconID = "rbxassetid://140472227728693",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Dizzy_Face"],
	SpecialData = {
		HeadType = "HeadSunken",
	}
}

ItemDirectory["Happy_Face"] = {
	FlavorText = "Happy",
	Rarity = "Rare",
	IconID = "rbxassetid://112018613458937",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Happy_Face"],
	SpecialData = {
		HeadType = "HeadFlat",
	}
}

ItemDirectory["Normal_Face"] = {
	FlavorText = "Sappy",
	Rarity = "Rare",
	IconID = "rbxassetid://84163473506929",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Normal_Face"],
	SpecialData = {
		HeadType = "HeadSunken",
	}
}

ItemDirectory["Rounded_Eyes"] = {
	FlavorText = "Beady Eyes",
	Rarity = "Rare",
	IconID = "rbxassetid://112337697341357",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Rounded_Eyes"],
	SpecialData = {
		HeadType = "HeadFlat",
	}
}

ItemDirectory["Shocked_Face"] = {
	FlavorText = "Shook",
	Rarity = "Rare",
	IconID = "rbxassetid://133121760424704",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Shocked_Face"],
	SpecialData = {
		HeadType = "HeadFlat",
	}
}

ItemDirectory["Sleepy_Face"] = {
	FlavorText = "Eepy",
	Rarity = "Rare",
	IconID = "rbxassetid://137485660443238",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Sleepy_Face"],
	SpecialData = {
		HeadType = "HeadFlat",
	}
}

ItemDirectory["Smug"] = {
	FlavorText = "Smug",
	Rarity = "Rare",
	IconID = "rbxassetid://74843906824947",
	ItemType = "FacialExpressions",
	ItemModel = game.ReplicatedStorage.Cosmetics.FacialExpressions["Smug"],
	SpecialData = {
		HeadType = "HeadFlat",
	}
}

----------------------------------------------------------------------------------------------------
-- GLASSES
----------------------------------------------------------------------------------------------------

ItemDirectory["404_Vr"] = {
	FlavorText = "Error 404",
	Rarity = "Rare",
	IconID = "rbxassetid://78039431081369",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["404_Vr"],
	SpecialData = {}
}

ItemDirectory["Black_Sunglasses"] = {
	FlavorText = "Black Shades",
	Rarity = "Uncommon",
	IconID = "rbxassetid://114790375995563",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Black_Sunglasses"],
	SpecialData = {}
}

ItemDirectory["Carti"] = {
	FlavorText = "Clout Goggles",
	Rarity = "Rare",
	IconID = "rbxassetid://134171388854986",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Carti"],
	SpecialData = {}
}

ItemDirectory["Color_Vr"] = {
	FlavorText = "Error VR",
	Rarity = "Rare",
	IconID = "rbxassetid://107790693600798",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Color_Vr"],
	SpecialData = {}
}


ItemDirectory["Noise_Vr"] = {
	FlavorText = "Noise VR",
	Rarity = "Rare",
	IconID = "rbxassetid://84422098061349",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Noise_Vr"],
	SpecialData = {}
}

ItemDirectory["No_Face_Mask"] = {
	FlavorText = "No Face Mask",
	Rarity = "Rare",
	IconID = "rbxassetid://134089476773219",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["No_Face_Mask"],
	SpecialData = {}
}

ItemDirectory["Purple_Color_Vr"] = {
	FlavorText = "Purple Error VR",
	Rarity = "Rare",
	IconID = "rbxassetid://126721427529315",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Purple_Color_Vr"],
	SpecialData = {}
}

ItemDirectory["Sick_Glasses"] = {
	FlavorText = "Epic Shades",
	Rarity = "Legendary",
	IconID = "rbxassetid://93894936485711",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Sick_Glasses"],
	SpecialData = {}
}

ItemDirectory["Skull_Mask"] = {
	FlavorText = "Skull Mask",
	Rarity = "Rare",
	IconID = "rbxassetid://105095827119417",
	ItemType = "Glasses",
	ItemModel = game.ReplicatedStorage.Cosmetics.Glasses["Skull_Mask"],
	SpecialData = {}
}

----------------------------------------------------------------------------------------------------
-- HATS
----------------------------------------------------------------------------------------------------

ItemDirectory["Antlers"] = {
	FlavorText = "Antlers",
	Rarity = "Rare",
	IconID = "rbxassetid://105059030088376",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Antlers"],
	SpecialData = {}
}

ItemDirectory["Arrow_Heads"] = {
	FlavorText = "Arrow",
	Rarity = "Legendary",
	IconID = "rbxassetid://132930115224669",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Arrow_Heads"],
	SpecialData = {}
}

ItemDirectory["Bear_Ears"] = {
	FlavorText = "Bear Ears",
	Rarity = "Rare",
	IconID = "rbxassetid://100434315372914",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Bear_Ears"],
	SpecialData = {}
}

ItemDirectory["Beret"] = {
	FlavorText = "Beret",
	Rarity = "Uncommon",
	IconID = "rbxassetid://83878718386326",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Beret"],
	SpecialData = {}
}

ItemDirectory["Black_Beanie"] = {
	FlavorText = "Black Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://96778446375815",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Black_Beanie"],
	SpecialData = {}
}

ItemDirectory["Black_Bucket_Hat"] = {
	FlavorText = "Black Bucket Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://117686058763130",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Black_Bucket_Hat"],
	SpecialData = {}
}

ItemDirectory["Black_Cap"] = {
	FlavorText = "Black Cap",
	Rarity = "Common",
	IconID = "rbxassetid://121636036353008",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Black_Cap"],
	SpecialData = {}
}

ItemDirectory["Black_Durag"] = {
	FlavorText = "Black Durag",
	Rarity = "Uncommon",
	IconID = "rbxassetid://84554975495602",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Black_Durag"],
	SpecialData = {}
}

ItemDirectory["Black_Frog_Bucket_Hat"] = {
	FlavorText = "Black Frog Bucket Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://98947952993674",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Black_Frog_Bucket_Hat"],
	SpecialData = {}
}

ItemDirectory["Black_Ninja_Headband"] = {
	FlavorText = "Black Ninja Headband",
	Rarity = "Rare",
	IconID = "rbxassetid://88608477090164",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Black_Ninja_Headband"],
	SpecialData = {}
}

ItemDirectory["Blue_Durag"] = {
	FlavorText = "Blue Durag",
	Rarity = "Uncommon",
	IconID = "rbxassetid://72628423820181",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Blue_Durag"],
	SpecialData = {}
}

ItemDirectory["Bowl_Cut"] = {
	FlavorText = "Bowl Cut",
	Rarity = "Rare",
	IconID = "rbxassetid://97938899377771",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Bowl_Cut"],
	SpecialData = {}
}

ItemDirectory["Cow_Boy_Hat"] = {
	FlavorText = "Cowboy Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://82747728382926",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Cow_Boy_Hat"],
	SpecialData = {}
}

ItemDirectory["Dunce_Hat"] = {
	FlavorText = "Dunce Cap",
	Rarity = "Legendary",
	IconID = "rbxassetid://74011908453253",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Dunce_Hat"],
	SpecialData = {}
}

ItemDirectory["Golden_Bowl_Cut"] = {
	FlavorText = "Golden Bowl Cut",
	Rarity = "Legendary",
	IconID = "rbxassetid://71896275427812",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Golden_Bowl_Cut"],
	SpecialData = {}
}

ItemDirectory["Golden_Crown"] = {
	FlavorText = "Golden Crown",
	Rarity = "Legendary",
	IconID = "rbxassetid://114861141549797",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Golden_Crown"],
	SpecialData = {}
}

ItemDirectory["Green_Beanie"] = {
	FlavorText = "Green Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://97517003884676",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Green_Beanie"],
	SpecialData = {}
}

ItemDirectory["Halo"] = {
	FlavorText = "Halo",
	Rarity = "Legendary",
	IconID = "rbxassetid://128747894627088",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Halo"],
	SpecialData = {}
}

ItemDirectory["Headphones"] = {
	FlavorText = "Black Headphones",
	Rarity = "Rare",
	IconID = "rbxassetid://113629825912425",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Headphones"],
	SpecialData = {}
}

ItemDirectory["Ice_Crown"] = {
	FlavorText = "Ice Crown",
	Rarity = "Legendary",
	IconID = "rbxassetid://138905439630366",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Ice_Crown"],
	SpecialData = {}
}

ItemDirectory["Laurel"] = {
	FlavorText = "Laurel",
	Rarity = "Legendary",
	IconID = "rbxassetid://113357563637169",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Laurel"],
	SpecialData = {}
}

ItemDirectory["Pumpkin_Head"] = {
	FlavorText = "Pumpkin Head",
	Rarity = "Rare",
	IconID = "rbxassetid://117428311995899",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Pumpkin_Head"],
	SpecialData = {}
}

ItemDirectory["Red_Beanie"] = {
	FlavorText = "Red Beanie",
	Rarity = "Common",
	IconID = "rbxassetid://100054583433601",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Red_Beanie"],
	SpecialData = {}
}

ItemDirectory["Red_Cap"] = {
	FlavorText = "Red Cap",
	Rarity = "Common",
	IconID = "rbxassetid://78675166975979",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Red_Cap"],
	SpecialData = {}
}

ItemDirectory["Red_Durag"] = {
	FlavorText = "Red Durag",
	Rarity = "Uncommon",
	IconID = "rbxassetid://134536607619497",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Red_Durag"],
	SpecialData = {}
}

ItemDirectory["Red_Ninja_Headband"] = {
	FlavorText = "Red Ninja Headband",
	Rarity = "Rare",
	IconID = "rbxassetid://109729971927079",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Red_Ninja_Headband"],
	SpecialData = {}
}

ItemDirectory["Sardonic"] = {
	FlavorText = "Mushroom",
	Rarity = "Rare",
	IconID = "rbxassetid://104549036892310",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Sardonic"],
	SpecialData = {}
}

ItemDirectory["Sombrero"] = {
	FlavorText = "Sombrero",
	Rarity = "Uncommon",
	IconID = "rbxassetid://120303458175312",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Sombrero"],
	SpecialData = {}
}

ItemDirectory["Tophat"] = {
	FlavorText = "Top Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://96266873784384",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Tophat"],
	SpecialData = {}
}

ItemDirectory["Ushanka"] = {
	FlavorText = "Cozy Hat",
	Rarity = "Uncommon",
	IconID = "rbxassetid://104838787373607",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Ushanka"],
	SpecialData = {}
}

ItemDirectory["Witch_Hat"] = {
	FlavorText = "Witch Hat",
	Rarity = "Rare",
	IconID = "rbxassetid://90003963069056",
	ItemType = "Hats",
	ItemModel = game.ReplicatedStorage.Cosmetics.Hats["Witch_Hat"],
	SpecialData = {}
}

----------------------------------------------------------------------------------------------------
-- SHIRTS
----------------------------------------------------------------------------------------------------

ItemDirectory["Angel_Wings"] = {
	FlavorText = "Angel Wings",
	Rarity = "Legendary",
	IconID = "rbxassetid://72520665576011",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Angel_Wings"],
	SpecialData = {}
}

ItemDirectory["Basketball_Vest"] = {
	FlavorText = "Basketball Jersey",
	Rarity = "Rare",
	IconID = "rbxassetid://128538981435956",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Basketball_Vest"],
	SpecialData = {}
}

ItemDirectory["Black_Bandana"] = {
	FlavorText = "Black Bandana",
	Rarity = "Uncommon",
	IconID = "rbxassetid://88863036550859",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Black_Bandana"],
	SpecialData = {}
}

ItemDirectory["Black_Bow_Tie"] = {
	FlavorText = "Black Bow Tie",
	Rarity = "Rare",
	IconID = "rbxassetid://136832222383040",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Black_Bow_Tie"],
	SpecialData = {}
}

ItemDirectory["Black_Closed_Hoodie"] = {
	FlavorText = "Black Cozy Hoodie",
	Rarity = "Uncommon",
	IconID = "rbxassetid://99068874385664",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Black_Closed_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Black_Kimono"] = {
	FlavorText = "Black Kimono",
	Rarity = "Rare",
	IconID = "rbxassetid://134387848922666",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Black_Kimono"],
	SpecialData = {}
}

ItemDirectory["Black_Tshirt"] = {
	FlavorText = "Black Tshirt",
	Rarity = "Common",
	IconID = "rbxassetid://95091225484918",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Black_Tshirt"],
	SpecialData = {}
}

ItemDirectory["Blue_Bandana"] = {
	FlavorText = "Blue Bandana",
	Rarity = "Common",
	IconID = "rbxassetid://89699035874274",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Blue_Bandana"],
	SpecialData = {}
}

ItemDirectory["Blue_Bomber"] = {
	FlavorText = "Blue Jacket",
	Rarity = "Uncommon",
	IconID = "rbxassetid://126013138596498",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Blue_Bomber"],
	SpecialData = {}
}

ItemDirectory["Blue_Closed_Hoodie"] = {
	FlavorText = "Blue Cozy Hoodie",
	Rarity = "Uncommon",
	IconID = "rbxassetid://136415881686851",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Blue_Closed_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Blue_Flower_Chain"] = {
	FlavorText = "Blue Lei",
	Rarity = "Rare",
	IconID = "rbxassetid://134560850460864",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Blue_Flower_Chain"],
	SpecialData = {}
}

ItemDirectory["Blue_Hoodie"] = {
	FlavorText = "Blue Hoodie",
	Rarity = "Common",
	IconID = "rbxassetid://127742574524769",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Blue_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Blue_Suit"] = {
	FlavorText = "Blue Suit",
	Rarity = "Rare",
	IconID = "rbxassetid://123975776156116",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Blue_Suit"],
	SpecialData = {}
}

ItemDirectory["Cozy_Knitted_Sweater"] = {
	FlavorText = "Cozy Sweater",
	Rarity = "Uncommon",
	IconID = "rbxassetid://74495952673501",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Cozy_Knitted_Sweater"],
	SpecialData = {}
}

ItemDirectory["Dirty_Vest"] = {
	FlavorText = "Dirty Tanktop",
	Rarity = "Legendary",
	IconID = "rbxassetid://86502991881754",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Dirty_Vest"],
	SpecialData = {}
}

ItemDirectory["Dungarees"] = {
	FlavorText = "Overalls",
	Rarity = "Rare",
	IconID = "rbxassetid://129923284707114",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Dungarees"],
	SpecialData = {}
}

ItemDirectory["Golden_Bomber_Jacket"] = {
	FlavorText = "Golden Jacket",
	Rarity = "Legendary",
	IconID = "rbxassetid://91063739510155",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Golden_Bomber_Jacket"],
	SpecialData = {}
}

ItemDirectory["Golden_Chain"] = {
	FlavorText = "Golden Chain",
	Rarity = "Legendary",
	IconID = "rbxassetid://78379759877901",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Golden_Chain"],
	SpecialData = {}
}

ItemDirectory["Golden_Robe"] = {
	FlavorText = "Golden Robe",
	Rarity = "Legendary",
	IconID = "rbxassetid://80891570754845",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Golden_Robe"],
	SpecialData = {}
}

ItemDirectory["Golden_Suit"] = {
	FlavorText = "Golden Suit",
	Rarity = "Legndary",
	IconID = "rbxassetid://96853148722671",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Golden_Suit"],
	SpecialData = {}
}

ItemDirectory["Green_Kimono"] = {
	FlavorText = "Green Kimono",
	Rarity = "Rare",
	IconID = "rbxassetid://94533961332811",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Green_Kimono"],
	SpecialData = {}
}

ItemDirectory["Green_Scarf"] = {
	FlavorText = "Green Scarf",
	Rarity = "Common",
	IconID = "rbxassetid://79212840352725",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Green_Scarf"],
	SpecialData = {}
}

ItemDirectory["Green_Tshirt"] = {
	FlavorText = "Green Tshirt",
	Rarity = "Common",
	IconID = "rbxassetid://71920187168724",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Green_Tshirt"],
	SpecialData = {}
}

ItemDirectory["Ice_Bomberjacket"] = {
	FlavorText = "Ice Jacket",
	Rarity = "Legendary",
	IconID = "rbxassetid://87922476841619",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Ice_Bomberjacket"],
	SpecialData = {}
}

ItemDirectory["Navy_Kimono"] = {
	FlavorText = "Navy Kimono",
	Rarity = "Rare",
	IconID = "rbxassetid://113046198051164",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Navy_Kimono"],
	SpecialData = {}
}

ItemDirectory["Orange_Flower_Chain"] = {
	FlavorText = "Orange Lei",
	Rarity = "Rare",
	IconID = "rbxassetid://91462796545006",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Orange_Flower_Chain"],
	SpecialData = {}
}

ItemDirectory["Orange_Tshirt"] = {
	FlavorText = "Orange Tshirt",
	Rarity = "Common",
	IconID = "rbxassetid://103337090040889",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Orange_Tshirt"],
	SpecialData = {}
}

ItemDirectory["Pink_Kimono"] = {
	FlavorText = "Pink Kimono",
	Rarity = "Rare",
	IconID = "rbxassetid://100346144474612",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Pink_Kimono"],
	SpecialData = {}
}

ItemDirectory["Pink_Scarf"] = {
	FlavorText = "Pink Scarf",
	Rarity = "Common",
	IconID = "rbxassetid://71198699101423",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Pink_Scarf"],
	SpecialData = {}
}

ItemDirectory["Poncho"] = {
	FlavorText = "Poncho",
	Rarity = "Rare",
	IconID = "rbxassetid://102274540331298",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Poncho"],
	SpecialData = {}
}

ItemDirectory["Purple_Bomber"] = {
	FlavorText = "Purple Jacket",
	Rarity = "Uncommon",
	IconID = "rbxassetid://104096324819399",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Purple_Bomber"],
	SpecialData = {}
}

ItemDirectory["Purple_Closed_Hoodie"] = {
	FlavorText = "Purple Cozy Hoodie",
	Rarity = "Uncommon",
	IconID = "rbxassetid://103412966577744",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Purple_Closed_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Purple_Flower_Chain"] = {
	FlavorText = "Purple Lei",
	Rarity = "Rare",
	IconID = "rbxassetid://102001388856417",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Purple_Flower_Chain"],
	SpecialData = {}
}

ItemDirectory["Purple_Hoodie"] = {
	FlavorText = "Purple Hoodie",
	Rarity = "Common",
	IconID = "rbxassetid://117816935840449",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Purple_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Purple_Tshirt"] = {
	FlavorText = "Purple Tshirt",
	Rarity = "Common",
	IconID = "rbxassetid://114039902602395",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Purple_Tshirt"],
	SpecialData = {}
}

ItemDirectory["Red_Bandana"] = {
	FlavorText = "Red Bandana",
	Rarity = "Uncommon",
	IconID = "rbxassetid://109118123995151",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Red_Bandana"],
	SpecialData = {}
}

ItemDirectory["Red_Bomber"] = {
	FlavorText = "Red Jacket",
	Rarity = "Uncommon",
	IconID = "rbxassetid://91554366822384",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Red_Bomber"],
	SpecialData = {}
}

ItemDirectory["Red_Bow_Tie"] = {
	FlavorText = "Red Bow Tie",
	Rarity = "Rare",
	IconID = "rbxassetid://134300908797843",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Red_Bow_Tie"],
	SpecialData = {}
}

ItemDirectory["Red_Flannel"] = {
	FlavorText = "Red Flannel",
	Rarity = "Uncommon",
	IconID = "rbxassetid://105256784731401",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Red_Flannel"],
	SpecialData = {}
}

ItemDirectory["Red_Hoodie"] = {
	FlavorText = "Red Hoodie",
	Rarity = "Common",
	IconID = "rbxassetid://136455344749229",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Red_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Red_Tshirt"] = {
	FlavorText = "Red Tshirt",
	Rarity = "Common",
	IconID = "rbxassetid://97484952155071",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Red_Tshirt"],
	SpecialData = {}
}

ItemDirectory["Tie_Dye_Tshirt"] = {
	FlavorText = "Tie Dye Tshirt",
	Rarity = "Legendary",
	IconID = "rbxassetid://82893812040756",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Tie_Dye_Tshirt"],
	SpecialData = {}
}

ItemDirectory["Trackie"] = {
	FlavorText = "Tracksuit",
	Rarity = "Rare",
	IconID = "rbxassetid://80340436963216",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Trackie"],
	SpecialData = {}
}

ItemDirectory["White_Kimono"] = {
	FlavorText = "White Kimono",
	Rarity = "Rare",
	IconID = "rbxassetid://70912909858203",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["White_Kimono"],
	SpecialData = {}
}

ItemDirectory["White_Vest"] = {
	FlavorText = "White Tank Top",
	Rarity = "Common",
	IconID = "rbxassetid://113281666447990",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["White_Vest"],
	SpecialData = {}
}

ItemDirectory["Yellow_Bomber"] = {
	FlavorText = "Orange Jacket",
	Rarity = "Uncommon",
	IconID = "rbxassetid://110690491852761",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Yellow_Bomber"],
	SpecialData = {}
}

ItemDirectory["Yellow_Closed_Hoodie"] = {
	FlavorText = "Orange Cozy Hoodie", --dont ask
	Rarity = "Uncommon",
	IconID = "rbxassetid://77134263160978",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Yellow_Closed_Hoodie"],
	SpecialData = {}
}

ItemDirectory["Yellow_Flannel"] = {
	FlavorText = "Yellow Flannel",
	Rarity = "Uncommon",
	IconID = "rbxassetid://121000466094643",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Yellow_Flannel"],
	SpecialData = {}
}

ItemDirectory["Yellow_Hoodie"] = {
	FlavorText = "Orange Hoodie", --dont ask
	Rarity = "Common",
	IconID = "rbxassetid://124545688460913",
	ItemType = "Shirts",
	ItemModel = game.ReplicatedStorage.Cosmetics.Shirts["Yellow_Hoodie"],
	SpecialData = {}
}

----------------------------------------------------------------------------------------------------
-- Trails
----------------------------------------------------------------------------------------------------

ItemDirectory["BeachTrail"] = {
	FlavorText = "Beach Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://72867248033683",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["BlackTrail"] = {
	FlavorText = "Black Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://107434667860425",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["BlueTrail"] = {
	FlavorText = "Blue Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://89139749313905",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["CloudyTrail"] = {
	FlavorText = "Cloudy Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://106558878406695",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["CoinTrail"] = {
	FlavorText = "Coin Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://76812718905161",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["EerieTrail"] = {
	FlavorText = "Eerie Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://136417795869020",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["FireTrail"] = {
	FlavorText = "Fire Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://81555707255577",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["GreenTrail"] = {
	FlavorText = "Green Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://112013041455993",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["IceTrail"] = {
	FlavorText = "Ice Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://99998165719771",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["LightningTrail"] = {
	FlavorText = "Lightning Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://135816809529510",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["OrangeTrail"] = {
	FlavorText = "Orange Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://100182200754289",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["PinkTrail"] = {
	FlavorText = "Pink Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://79077109735280",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["PurpleTrail"] = {
	FlavorText = "Purple Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://133958320616515",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["RainbowTrail"] = {
	FlavorText = "Rainbow Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://127674825195783",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["RedTrail"] = {
	FlavorText = "Red Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://87404804253019",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["RobuxTrail"] = {
	FlavorText = "Robux Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://128116345469331",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["TixTrail"] = {
	FlavorText = "Tix Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://135108083385548",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["ToothpasteTrail"] = {
	FlavorText = "Toothpaste Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://110904959254530",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["WaterTrail"] = {
	FlavorText = "Water Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://123673198441825",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["WatermelonTrail"] = {
	FlavorText = "Watermelon Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://107165464325684",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["WhiteTrail"] = {
	FlavorText = "White Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://128789499167945",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}

ItemDirectory["YellowTrail"] = {
	FlavorText = "Yellow Trail",
	Rarity = "Legendary",
	IconID = "rbxassetid://108974830662351",
	ItemType = "Trails",
	ItemModel = nil,
	SpecialData = {}
}


----------------------------------------------------------------------------------------------------
-- MISCELLANEOUS
----------------------------------------------------------------------------------------------------

ItemDirectory["Coins"] = {
	FlavorText = "Coins",
	Rarity = "Legendary",
	IconID = "rbxassetid://126556997920262",
	ItemType = "Miscellaneous",
	ItemModel = nil,
	SpecialData = {}
}



----------------------------------------------------------------------------------------------------
-- Setup --
----------------------------------------------------------------------------------------------------
return ItemDirectory