
-- Constants --

local ModifierDirectory = {}


-- Directory Info --

ModifierDirectory.ActiveModifiers = {
	--"ClownModifier",
	"FartModifier",
	"GravityModifier",
	"InfiniteBoostsModifier",
	"GubbyModifier",
	"RainingSealsModifier",
	"InvulnerabilityModifier",
	"NightModeModifier",
	"BlockySappyModifier"
}

ModifierDirectory.InvulnerabilityModifier = {
	IconID = "rbxassetid://76053281764677",
	FlavorText = "Invulnerability",
	Description = "Smash through obstacles with ease!",
	Price = 19,
}

ModifierDirectory.RainingSealsModifier = {
	IconID = "rbxassetid://127963388345275",
	FlavorText = "Raining Seals",
	Description = "ITS RAINING SEALS!",
	Price = 19,
}

ModifierDirectory.ClownModifier = {
	IconID = "rbxassetid://120583969982335",
	FlavorText = "Clown Noses",
	Description = "All seals become clowns!",
	Price = 19,
}

ModifierDirectory.FartModifier = {
	IconID = "rbxassetid://79827117729473",
	FlavorText = "Farting Seals",
	Description = "All seals start farting!",
	Price = 19,
}

ModifierDirectory.GravityModifier = {
	IconID = "rbxassetid://111070540811320",
	FlavorText = "Low Gravity",
	Description = "Low gravity is in effect!",
	Price = 19,
}

ModifierDirectory.InfiniteBoostsModifier = {
	IconID = "rbxassetid://101244756589056",
	FlavorText = "Infinite Boosts",
	Description = "Infinite Boost Fish!",
	Price = 19,
}

ModifierDirectory.GubbyModifier = {
	IconID = "rbxassetid://115233777642994",
	FlavorText = "GUBBY MODE",
	Description = "All seals become GUBBY!",
	Price = 19,
}

ModifierDirectory.NightModeModifier = {
	IconID = "rbxassetid://111070540811320",
	FlavorText = "Night Mode",
	Description = "Race under the cover of darkness!",
	Price = 19,
}

ModifierDirectory.BlockySappyModifier = {
	IconID = "rbxassetid://111070540811320",
	FlavorText = "BLOCKY MODE",
	Description = "All seals become BLOCKY!",
	Price = 19,
}


-- Setup --

return ModifierDirectory
